#!/bin/sh
GIT_ROOT="$(git rev-parse --show-toplevel)"
GITHOOK_DEFAULT_COMMITCHECK="$GIT_ROOT/.commit-check"
GITHOOK_DEFAULT_FILE="$GIT_ROOT/.gitdefault"

#---------------------------------------
# Import default settings and message formater
if [ -f "$GITHOOK_DEFAULT_FILE" ]; then
    . "$GITHOOK_DEFAULT_FILE"
else
    deckLinkFlag=false
    gerritChangeIdFlag=true
    commitCheckFlag=true
fi

# Detect if we're in a merge or rebase in progress
if [ -f "$GIT_DIR/MERGE_HEAD" ] || [ -f "$GIT_DIR/REBASE_MERGE_HEAD" ] || [ -f "$GIT_DIR/REBASE_APPLY_HEAD" ]; then
    isMergeInProgress=true
else
    isMergeInProgress=false
fi

if [ "$isMergeInProgress" = "true" ]; then
    COMMIT_MSG_DIRECTIVES_SHINC=.git/hooks/commit-msg-directives.shinc
    if [ -f "$COMMIT_MSG_DIRECTIVES_SHINC" ]; then
        . ${COMMIT_MSG_DIRECTIVES_SHINC}
    fi
fi
#---------------------------------------

exitcode=0
if [ "$commitCheckFlag" = true ]; then
    if [ -f "$GITHOOK_DEFAULT_COMMITCHECK" ]; then
	    . ${GITHOOK_DEFAULT_COMMITCHECK}
    else
	    echo "No check has been defined!"
    fi
fi
exit $exitcode
